import { beforeAll, describe, expect, it } from "vitest";
import { createMigratedDb, type Db } from "./pglite/harness";

let db: Db;

beforeAll(async () => {
  db = await createMigratedDb({ createServiceRole: true });
});

describe("hosted Supabase Data API grants", () => {
  it("grants the service role access to every application table", async () => {
    const result = await db.query<{ table_name: string; has_access: boolean }>(
      `select c.relname as table_name,
              has_table_privilege('service_role', c.oid, 'SELECT')
              and has_table_privilege('service_role', c.oid, 'INSERT')
              and has_table_privilege('service_role', c.oid, 'UPDATE')
              and has_table_privilege('service_role', c.oid, 'DELETE')
                as has_access
         from pg_class c
         join pg_namespace n on n.oid = c.relnamespace
        where n.nspname = 'public'
          and c.relkind = 'r'
        order by c.relname`,
    );

    expect(result.rows.map((row) => row.table_name)).toEqual([
      "audit_events",
      "bins",
      "inbound_sms_events",
      "notification_outbox",
      "queue_entries",
      "rentals",
      "reservations",
      "sessions",
      "students",
    ]);
    expect(result.rows.every((row) => row.has_access)).toBe(true);
  });

  it("denies browser roles EXECUTE on every public function", async () => {
    const result = await db.query<{
      function_name: string;
      anon_can_execute: boolean;
      authenticated_can_execute: boolean;
    }>(
      `select p.oid::regprocedure::text as function_name,
              has_function_privilege('anon', p.oid, 'EXECUTE')
                as anon_can_execute,
              has_function_privilege('authenticated', p.oid, 'EXECUTE')
                as authenticated_can_execute
         from pg_proc p
         join pg_namespace n on n.oid = p.pronamespace
        where n.nspname = 'public'
          and p.prokind = 'f'
        order by p.oid::regprocedure::text`,
    );

    expect(result.rows.length).toBeGreaterThan(0);
    expect(
      result.rows.filter(
        (row) => row.anon_can_execute || row.authenticated_can_execute,
      ),
    ).toEqual([]);
  });

  it("applies the same least-privilege defaults to future tables", async () => {
    await db.exec(`
      create table public.service_role_grant_probe (
        id bigint generated by default as identity primary key
      )
    `);

    const table = await db.query<{ has_access: boolean }>(
      `select has_table_privilege(
                'service_role',
                'public.service_role_grant_probe',
                'SELECT'
              )
              and has_table_privilege(
                'service_role',
                'public.service_role_grant_probe',
                'INSERT'
              )
              and has_table_privilege(
                'service_role',
                'public.service_role_grant_probe',
                'UPDATE'
              )
              and has_table_privilege(
                'service_role',
                'public.service_role_grant_probe',
                'DELETE'
              ) as has_access`,
    );
    const sequence = await db.query<{ has_access: boolean }>(
      `select has_sequence_privilege(
                'service_role',
                'public.service_role_grant_probe_id_seq',
                'USAGE'
              )
              and has_sequence_privilege(
                'service_role',
                'public.service_role_grant_probe_id_seq',
                'SELECT'
              ) as has_access`,
    );

    expect(table.rows[0].has_access).toBe(true);
    expect(sequence.rows[0].has_access).toBe(true);
  });
});
