import { beforeAll, describe, expect, it } from "vitest";
import { createMigratedDb, type Db } from "./pglite/harness";

let db: Db;

beforeAll(async () => {
  db = await createMigratedDb({ createServiceRole: true });
});

describe("hosted Supabase Data API grants", () => {
  it("grants the service role access to every application table", async () => {
    const result = await db.query<{ table_name: string; has_access: boolean }>(
      `select c.relname as table_name,
              has_table_privilege('service_role', c.oid, 'SELECT')
              and has_table_privilege('service_role', c.oid, 'INSERT')
              and has_table_privilege('service_role', c.oid, 'UPDATE')
              and has_table_privilege('service_role', c.oid, 'DELETE')
                as has_access
         from pg_class c
         join pg_namespace n on n.oid = c.relnamespace
        where n.nspname = 'public'
          and c.relkind = 'r'
        order by c.relname`,
    );

    expect(result.rows.map((row) => row.table_name)).toEqual([
      "audit_events",
      "bins",
      "inbound_sms_events",
      "notification_outbox",
      "queue_entries",
      "rate_limit_buckets",
      "rentals",
      "reservations",
      "sessions",
      "staff_web_sessions",
      "students",
    ]);
    expect(result.rows.every((row) => row.has_access)).toBe(true);
  });

  it("proves service_role BYPASSRLS returns protected rows instead of an empty result", async () => {
    const identity = "7".repeat(64);
    await db.query(
      `insert into public.rate_limit_buckets (
         scope, identity_hash, request_count, window_started_at, expires_at
       ) values ('service_role_probe', $1, 1, now(), now() + interval '1 minute')`,
      [identity],
    );

    let rows: Array<{ identity_hash: string }> = [];
    try {
      await db.exec("set role service_role");
      const result = await db.query<{ identity_hash: string }>(
        `select identity_hash from public.rate_limit_buckets
         where scope = 'service_role_probe'`,
      );
      rows = result.rows;
    } finally {
      await db.exec("reset role");
    }

    expect(rows).toEqual([{ identity_hash: identity }]);
  });

  it("denies browser roles EXECUTE on every public function", async () => {
    const result = await db.query<{
      function_name: string;
      anon_can_execute: boolean;
      authenticated_can_execute: boolean;
    }>(
      `select p.oid::regprocedure::text as function_name,
              has_function_privilege('anon', p.oid, 'EXECUTE')
                as anon_can_execute,
              has_function_privilege('authenticated', p.oid, 'EXECUTE')
                as authenticated_can_execute
         from pg_proc p
         join pg_namespace n on n.oid = p.pronamespace
        where n.nspname = 'public'
          and p.prokind = 'f'
        order by p.oid::regprocedure::text`,
    );

    expect(result.rows.length).toBeGreaterThan(0);
    expect(
      result.rows.filter(
        (row) => row.anon_can_execute || row.authenticated_can_execute,
      ),
    ).toEqual([]);
  });

  it("denies browser roles access to every public table, view, and sequence", async () => {
    const relations = await db.query<{
      relation_name: string;
      anon_can_select: boolean;
      authenticated_can_select: boolean;
    }>(
      `select c.relname as relation_name,
              has_table_privilege('anon', c.oid, 'SELECT') as anon_can_select,
              has_table_privilege('authenticated', c.oid, 'SELECT')
                as authenticated_can_select
         from pg_class c
         join pg_namespace n on n.oid = c.relnamespace
        where n.nspname = 'public'
          and c.relkind in ('r', 'v', 'm')
        order by c.relname`,
    );
    const sequences = await db.query<{
      sequence_name: string;
      anon_can_use: boolean;
      authenticated_can_use: boolean;
    }>(
      `select c.relname as sequence_name,
              has_sequence_privilege('anon', c.oid, 'USAGE') as anon_can_use,
              has_sequence_privilege('authenticated', c.oid, 'USAGE')
                as authenticated_can_use
         from pg_class c
         join pg_namespace n on n.oid = c.relnamespace
        where n.nspname = 'public'
          and c.relkind = 'S'
        order by c.relname`,
    );

    expect(relations.rows.length).toBeGreaterThan(0);
    expect(
      relations.rows.filter(
        (row) => row.anon_can_select || row.authenticated_can_select,
      ),
    ).toEqual([]);
    expect(
      sequences.rows.filter(
        (row) => row.anon_can_use || row.authenticated_can_use,
      ),
    ).toEqual([]);
  });

  it("applies the same least-privilege defaults to future tables", async () => {
    await db.exec(`
      create table public.service_role_grant_probe (
        id bigint generated by default as identity primary key
      )
    `);
    await db.exec(`
      create function public.browser_default_probe()
      returns integer
      language sql
      as 'select 1'
    `);

    const table = await db.query<{ has_access: boolean }>(
      `select has_table_privilege(
                'service_role',
                'public.service_role_grant_probe',
                'SELECT'
              )
              and has_table_privilege(
                'service_role',
                'public.service_role_grant_probe',
                'INSERT'
              )
              and has_table_privilege(
                'service_role',
                'public.service_role_grant_probe',
                'UPDATE'
              )
              and has_table_privilege(
                'service_role',
                'public.service_role_grant_probe',
                'DELETE'
              ) as has_access`,
    );
    const sequence = await db.query<{ has_access: boolean }>(
      `select has_sequence_privilege(
                'service_role',
                'public.service_role_grant_probe_id_seq',
                'USAGE'
              )
              and has_sequence_privilege(
                'service_role',
                'public.service_role_grant_probe_id_seq',
                'SELECT'
              ) as has_access`,
    );

    expect(table.rows[0].has_access).toBe(true);
    expect(sequence.rows[0].has_access).toBe(true);
    const browserDefaults = await db.query<{
      anon_table: boolean;
      authenticated_table: boolean;
      anon_sequence: boolean;
      authenticated_sequence: boolean;
      anon_function: boolean;
      authenticated_function: boolean;
    }>(
      `select has_table_privilege(
                'anon', 'public.service_role_grant_probe', 'SELECT'
              ) as anon_table,
              has_table_privilege(
                'authenticated', 'public.service_role_grant_probe', 'SELECT'
              ) as authenticated_table,
              has_sequence_privilege(
                'anon', 'public.service_role_grant_probe_id_seq', 'USAGE'
              ) as anon_sequence,
              has_sequence_privilege(
                'authenticated',
                'public.service_role_grant_probe_id_seq',
                'USAGE'
              ) as authenticated_sequence,
              has_function_privilege(
                'anon', 'public.browser_default_probe()', 'EXECUTE'
              ) as anon_function,
              has_function_privilege(
                'authenticated',
                'public.browser_default_probe()',
                'EXECUTE'
              ) as authenticated_function`,
    );
    expect(browserDefaults.rows[0]).toEqual({
      anon_table: false,
      authenticated_table: false,
      anon_sequence: false,
      authenticated_sequence: false,
      anon_function: false,
      authenticated_function: false,
    });
  });
});
