-- Panther Carts — Ticket 6: authentication and data protection
--
-- Browser roles remain denied by default. Trusted server operations use the
-- service role only after application-level admin or staff authorization.
-- Staff bearer credentials are represented by keyed verifier hashes; only
-- authenticated ciphertext is retained for the admin's required redisplay.

-- ---------------------------------------------------------------------------
-- Staff credentials
-- ---------------------------------------------------------------------------

alter table public.sessions
  add column staff_link_hash text,
  add column staff_access_code_ciphertext text,
  add column staff_access_code_hash text,
  add column staff_credential_version text not null default 'legacy-sha256';

-- Existing high-entropy staff links remain usable after this migration, but
-- their plaintext is scrubbed and therefore cannot be redisplayed. New
-- credentials use application-keyed HMAC verifiers and authenticated
-- ciphertext generated by trusted server code.
update public.sessions
set staff_link_hash = encode(sha256(convert_to(staff_code, 'UTF8')), 'hex'),
    staff_code = 'protected-legacy-' || replace(id::text, '-', ''),
    staff_credential_version = 'legacy-sha256';

alter table public.sessions
  alter column staff_link_hash set not null,
  add constraint sessions_staff_link_hash_format
    check (staff_link_hash ~ '^[a-f0-9]{64}$'),
  add constraint sessions_staff_access_code_hash_format
    check (
      staff_access_code_hash is null
      or staff_access_code_hash ~ '^[a-f0-9]{64}$'
    ),
  add constraint sessions_staff_credential_version_known
    check (staff_credential_version in ('legacy-sha256', 'hmac-v1')),
  add constraint sessions_staff_access_code_pair
    check (
      (staff_access_code_ciphertext is null) =
      (staff_access_code_hash is null)
    );

create unique index sessions_staff_link_hash_uidx
  on public.sessions (staff_link_hash);

create unique index sessions_staff_access_code_hash_uidx
  on public.sessions (staff_access_code_hash)
  where staff_access_code_hash is not null;

-- The browser holds only the random token. The database stores its keyed
-- verifier and authoritative session binding, so a forged session id or a
-- copied cookie from another session cannot choose the target session.
create table public.staff_web_sessions (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.sessions (id) on delete cascade,
  token_hash text not null unique,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  revoked_at timestamptz,
  constraint staff_web_sessions_token_hash_format
    check (token_hash ~ '^[a-f0-9]{64}$'),
  constraint staff_web_sessions_expiry_after_creation
    check (expires_at > created_at)
);

create index staff_web_sessions_active_token_idx
  on public.staff_web_sessions (token_hash, expires_at)
  where revoked_at is null;

-- ---------------------------------------------------------------------------
-- Durable, atomic rate limiting
-- ---------------------------------------------------------------------------

create table public.rate_limit_buckets (
  scope text not null,
  identity_hash text not null,
  request_count integer not null,
  window_started_at timestamptz not null,
  expires_at timestamptz not null,
  primary key (scope, identity_hash),
  constraint rate_limit_scope_format
    check (scope ~ '^[a-z][a-z0-9_]{1,63}$'),
  constraint rate_limit_identity_hash_format
    check (identity_hash ~ '^[a-f0-9]{64}$'),
  constraint rate_limit_request_count_positive
    check (request_count > 0),
  constraint rate_limit_expiry_after_start
    check (expires_at > window_started_at)
);

create index rate_limit_buckets_expiry_idx
  on public.rate_limit_buckets (expires_at);

create or replace function public.consume_rate_limit(
  p_scope text,
  p_identity_hash text,
  p_limit integer,
  p_window_seconds integer
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_now timestamptz := clock_timestamp();
  v_bucket public.rate_limit_buckets;
begin
  if p_scope is null or p_scope !~ '^[a-z][a-z0-9_]{1,63}$'
     or p_identity_hash is null
     or p_identity_hash !~ '^[a-f0-9]{64}$'
     or p_limit is null or p_limit < 1 or p_limit > 10000
     or p_window_seconds is null
     or p_window_seconds < 1 or p_window_seconds > 86400 then
    raise exception 'PANTHER_CARTS:INVALID_RATE_LIMIT_INPUT';
  end if;

  insert into public.rate_limit_buckets (
    scope,
    identity_hash,
    request_count,
    window_started_at,
    expires_at
  ) values (
    p_scope,
    p_identity_hash,
    1,
    v_now,
    v_now + make_interval(secs => p_window_seconds)
  )
  on conflict (scope, identity_hash) do update
  set request_count = case
        when public.rate_limit_buckets.expires_at <= v_now then 1
        else least(public.rate_limit_buckets.request_count + 1, p_limit + 1)
      end,
      window_started_at = case
        when public.rate_limit_buckets.expires_at <= v_now then v_now
        else public.rate_limit_buckets.window_started_at
      end,
      expires_at = case
        when public.rate_limit_buckets.expires_at <= v_now
          then v_now + make_interval(secs => p_window_seconds)
        else public.rate_limit_buckets.expires_at
      end
  returning * into v_bucket;

  -- Lock the current identity first (in the upsert above), then opportunistically
  -- remove other expired identities. This consistent ordering prevents two
  -- callers from deleting each other's rows before each upserts its own row.
  -- SKIP LOCKED keeps the non-authoritative cleanup from waiting on contention.
  delete from public.rate_limit_buckets
  where ctid in (
    select ctid
    from public.rate_limit_buckets
    where expires_at <= v_now
      and not (scope = p_scope and identity_hash = p_identity_hash)
    order by expires_at
    limit 100
    for update skip locked
  );

  return jsonb_build_object(
    'allowed', v_bucket.request_count <= p_limit,
    'remaining', greatest(0, p_limit - v_bucket.request_count),
    'retry_after_seconds', case
      when v_bucket.request_count <= p_limit then 0
      else greatest(
        1,
        ceil(extract(epoch from (v_bucket.expires_at - v_now)))::integer
      )
    end
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- Staff credential exchange
-- ---------------------------------------------------------------------------

create or replace function public.create_staff_web_session(
  p_candidate_hashes text[],
  p_session_token_hash text,
  p_expires_at timestamptz
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_session public.sessions;
  v_match_count integer;
  v_web_session public.staff_web_sessions;
begin
  if p_candidate_hashes is null
     or cardinality(p_candidate_hashes) < 1
     or cardinality(p_candidate_hashes) > 2
     or exists (
       select 1
       from unnest(p_candidate_hashes) as candidate(value)
       where value is null or value !~ '^[a-f0-9]{64}$'
     )
     or p_session_token_hash is null
     or p_session_token_hash !~ '^[a-f0-9]{64}$'
     or p_expires_at is null
     or p_expires_at <= now()
     or p_expires_at > now() + interval '12 hours 5 minutes' then
    raise exception 'PANTHER_CARTS:INVALID_STAFF_CREDENTIAL';
  end if;

  select count(*)::integer into v_match_count
  from public.sessions
  where staff_link_hash = any(p_candidate_hashes)
     or staff_access_code_hash = any(p_candidate_hashes);

  if v_match_count <> 1 then
    raise exception 'PANTHER_CARTS:INVALID_STAFF_CREDENTIAL';
  end if;

  select * into v_session
  from public.sessions
  where staff_link_hash = any(p_candidate_hashes)
     or staff_access_code_hash = any(p_candidate_hashes)
  for update;

  if v_session.status <> 'ACTIVE' then
    raise exception 'PANTHER_CARTS:SESSION_NOT_ACTIVE';
  end if;

  insert into public.staff_web_sessions (
    session_id,
    token_hash,
    expires_at
  ) values (
    v_session.id,
    p_session_token_hash,
    p_expires_at
  ) returning * into v_web_session;

  -- Credential matching, the authoritative session lock, and the new token
  -- insert all happen before cleanup. This matches admin_end_session's session
  -- then web-session lock order and prevents invalid credentials from driving
  -- cleanup work.
  delete from public.staff_web_sessions
  where id in (
    select id
    from public.staff_web_sessions
    where expires_at <= now() or revoked_at is not null
    order by coalesce(revoked_at, expires_at)
    limit 100
    for update skip locked
  );

  return jsonb_build_object(
    'session_id', v_web_session.session_id,
    'expires_at', v_web_session.expires_at
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- Admin session creation with protected staff credentials
-- ---------------------------------------------------------------------------

revoke execute on function public.admin_create_session(
  text, integer, integer, text
) from public;

drop function public.admin_create_session(text, integer, integer, text);

create function public.admin_create_session(
  p_name text,
  p_rental_duration_minutes integer,
  p_pickup_window_minutes integer,
  p_idempotency_key text,
  p_student_code text,
  p_staff_link_ciphertext text,
  p_staff_link_hash text,
  p_staff_access_code_ciphertext text,
  p_staff_access_code_hash text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_session public.sessions;
  v_fingerprint text;
begin
  if p_idempotency_key is null or btrim(p_idempotency_key) = '' then
    raise exception 'PANTHER_CARTS:IDEMPOTENCY_KEY_REQUIRED';
  end if;
  if p_name is null or btrim(p_name) = ''
     or p_rental_duration_minutes is null or p_rental_duration_minutes <= 0
     or p_pickup_window_minutes is null or p_pickup_window_minutes <= 0
     or p_student_code is null
     or p_student_code !~ '^signup-[a-f0-9]{32}$'
     or p_staff_link_ciphertext is null
     or length(p_staff_link_ciphertext) > 2048
     or p_staff_link_hash is null
     or p_staff_link_hash !~ '^[a-f0-9]{64}$'
     or p_staff_access_code_ciphertext is null
     or length(p_staff_access_code_ciphertext) > 2048
     or p_staff_access_code_hash is null
     or p_staff_access_code_hash !~ '^[a-f0-9]{64}$' then
    raise exception 'PANTHER_CARTS:INVALID_ADMIN_INPUT';
  end if;

  perform public.lock_idempotency_key('admin_create_session_open', 'singleton');
  perform public.lock_idempotency_key('admin_create_session', p_idempotency_key);
  v_fingerprint := jsonb_build_object(
    'name', btrim(p_name),
    'rental_duration_minutes', p_rental_duration_minutes,
    'pickup_window_minutes', p_pickup_window_minutes
  )::text;

  select * into v_session
  from public.sessions
  where creation_idempotency_key = p_idempotency_key;

  if v_session.id is not null then
    if v_session.creation_request_fingerprint is distinct from v_fingerprint then
      raise exception 'PANTHER_CARTS:IDEMPOTENCY_CONFLICT';
    end if;
    return jsonb_build_object(
      'session', to_jsonb(v_session),
      'idempotent_replay', true
    );
  end if;

  if exists (
    select 1
    from public.sessions
    where creation_idempotency_key is not null
      and status in ('DRAFT', 'ACTIVE')
  ) then
    raise exception 'PANTHER_CARTS:SESSION_ALREADY_OPEN';
  end if;

  insert into public.sessions (
    name,
    status,
    student_code,
    staff_code,
    staff_link_hash,
    staff_access_code_ciphertext,
    staff_access_code_hash,
    staff_credential_version,
    rental_duration_minutes,
    pickup_window_minutes,
    creation_idempotency_key,
    creation_request_fingerprint
  ) values (
    btrim(p_name),
    'DRAFT',
    p_student_code,
    p_staff_link_ciphertext,
    p_staff_link_hash,
    p_staff_access_code_ciphertext,
    p_staff_access_code_hash,
    'hmac-v1',
    p_rental_duration_minutes,
    p_pickup_window_minutes,
    p_idempotency_key,
    v_fingerprint
  ) returning * into v_session;

  insert into public.audit_events (
    session_id, actor_type, actor_id, action, entity_type, entity_id, metadata
  ) values (
    v_session.id,
    'ADMIN',
    'Admin dashboard',
    'SESSION_CREATED',
    'SESSION',
    v_session.id::text,
    jsonb_build_object(
      'rental_duration_minutes', p_rental_duration_minutes,
      'pickup_window_minutes', p_pickup_window_minutes
    )
  );

  return jsonb_build_object(
    'session', to_jsonb(v_session),
    'idempotent_replay', false
  );
end;
$$;

-- Ending a session immediately invalidates every derived staff browser
-- session, even if a cookie has not reached its normal expiry yet.
create or replace function public.admin_end_session(p_session_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_session public.sessions;
begin
  perform public.lock_session(p_session_id);

  select * into v_session
  from public.sessions
  where id = p_session_id
  for update;

  if v_session.id is null then
    raise exception 'PANTHER_CARTS:SESSION_NOT_FOUND';
  end if;
  if v_session.status = 'CLOSED' then
    update public.staff_web_sessions
    set revoked_at = coalesce(revoked_at, now())
    where session_id = p_session_id and revoked_at is null;
    return jsonb_build_object(
      'session', to_jsonb(v_session),
      'idempotent_replay', true
    );
  end if;
  if v_session.status <> 'ACTIVE' then
    raise exception 'PANTHER_CARTS:SESSION_NOT_ACTIVE';
  end if;

  update public.sessions
  set status = 'CLOSED', ended_at = coalesce(ended_at, now())
  where id = p_session_id
  returning * into v_session;

  update public.staff_web_sessions
  set revoked_at = coalesce(revoked_at, now())
  where session_id = p_session_id and revoked_at is null;

  insert into public.audit_events (
    session_id, actor_type, actor_id, action, entity_type, entity_id
  ) values (
    p_session_id,
    'ADMIN',
    'Admin dashboard',
    'SESSION_ENDED',
    'SESSION',
    p_session_id::text
  );

  return jsonb_build_object(
    'session', to_jsonb(v_session),
    'idempotent_replay', false
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- RLS, views, and Data API privileges
-- ---------------------------------------------------------------------------

alter table public.sessions force row level security;
alter table public.students force row level security;
alter table public.bins force row level security;
alter table public.queue_entries force row level security;
alter table public.reservations force row level security;
alter table public.rentals force row level security;
alter table public.notification_outbox force row level security;
alter table public.audit_events force row level security;
alter table public.inbound_sms_events force row level security;
alter table public.staff_web_sessions enable row level security;
alter table public.staff_web_sessions force row level security;
alter table public.rate_limit_buckets enable row level security;
alter table public.rate_limit_buckets force row level security;

do $$
declare
  v_table text;
  v_role text;
begin
  foreach v_table in array array[
    'sessions',
    'students',
    'bins',
    'queue_entries',
    'reservations',
    'rentals',
    'notification_outbox',
    'audit_events',
    'inbound_sms_events',
    'staff_web_sessions',
    'rate_limit_buckets'
  ] loop
    execute format(
      'create policy %I on public.%I as restrictive for all to public using (false) with check (false)',
      v_table || '_browser_deny',
      v_table
    );
    execute format('revoke all on table public.%I from public', v_table);
    foreach v_role in array array['anon', 'authenticated'] loop
      if exists (select 1 from pg_roles where rolname = v_role) then
        execute format('revoke all on table public.%I from %I', v_table, v_role);
      end if;
    end loop;
  end loop;

  foreach v_table in array array[
    'v_current_out_rentals',
    'v_current_late_rentals',
    'v_all_late_rentals',
    'v_inventory',
    'v_session_rentals',
    'v_current_waitlist'
  ] loop
    execute format('revoke all on table public.%I from public', v_table);
    foreach v_role in array array['anon', 'authenticated'] loop
      if exists (select 1 from pg_roles where rolname = v_role) then
        execute format('revoke all on table public.%I from %I', v_table, v_role);
      end if;
    end loop;
  end loop;

  execute 'revoke all on all sequences in schema public from public';
  execute 'alter default privileges for role postgres in schema public revoke all on tables from public';
  execute 'alter default privileges for role postgres in schema public revoke all on sequences from public';
  -- PostgreSQL's built-in PUBLIC execute grant is global. A per-schema REVOKE
  -- cannot override it, so remove it from the owner's global defaults.
  execute 'alter default privileges for role postgres revoke execute on functions from public';
  execute 'alter default privileges in schema public revoke all on tables from public';
  execute 'alter default privileges in schema public revoke all on sequences from public';
  execute 'alter default privileges revoke execute on functions from public';

  foreach v_role in array array['anon', 'authenticated'] loop
    if exists (select 1 from pg_roles where rolname = v_role) then
      execute format(
        'revoke all on all sequences in schema public from %I',
        v_role
      );
      execute format(
        'alter default privileges for role postgres in schema public revoke all on tables from %I',
        v_role
      );
      execute format(
        'alter default privileges for role postgres in schema public revoke all on sequences from %I',
        v_role
      );
      execute format(
        'alter default privileges for role postgres in schema public revoke execute on functions from %I',
        v_role
      );
      execute format(
        'alter default privileges in schema public revoke all on tables from %I',
        v_role
      );
      execute format(
        'alter default privileges in schema public revoke all on sequences from %I',
        v_role
      );
      execute format(
        'alter default privileges in schema public revoke execute on functions from %I',
        v_role
      );
    end if;
  end loop;

  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant select, insert, update, delete on public.staff_web_sessions to service_role';
    execute 'grant select, insert, update, delete on public.rate_limit_buckets to service_role';
  end if;
end;
$$;

-- The application does not consume Postgres Changes. Remove protected tables
-- from Supabase Realtime even if a previous environment added them manually;
-- this keeps PII and credential metadata out of the replication channel.
do $$
declare
  v_table text;
begin
  if exists (
    select 1 from pg_publication where pubname = 'supabase_realtime'
  ) then
    foreach v_table in array array[
      'sessions',
      'students',
      'bins',
      'queue_entries',
      'reservations',
      'rentals',
      'notification_outbox',
      'audit_events',
      'inbound_sms_events',
      'staff_web_sessions',
      'rate_limit_buckets'
    ] loop
      if exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = v_table
      ) then
        execute format(
          'alter publication supabase_realtime drop table public.%I',
          v_table
        );
      end if;
    end loop;
  end if;
end;
$$;

revoke execute on function public.consume_rate_limit(
  text, text, integer, integer
) from public;
revoke execute on function public.create_staff_web_session(
  text[], text, timestamptz
) from public;
revoke execute on function public.admin_create_session(
  text, integer, integer, text, text, text, text, text, text
) from public;
revoke execute on function public.admin_end_session(uuid) from public;

do $$
declare
  v_role text;
  v_function text;
begin
  foreach v_function in array array[
    'consume_rate_limit(text,text,integer,integer)',
    'create_staff_web_session(text[],text,timestamptz)',
    'admin_create_session(text,integer,integer,text,text,text,text,text,text)',
    'admin_end_session(uuid)'
  ] loop
    foreach v_role in array array['anon', 'authenticated'] loop
      if exists (select 1 from pg_roles where rolname = v_role) then
        execute format(
          'revoke execute on function public.%s from %I',
          v_function,
          v_role
        );
      end if;
    end loop;
    if exists (select 1 from pg_roles where rolname = 'service_role') then
      execute format(
        'grant execute on function public.%s to service_role',
        v_function
      );
    end if;
  end loop;
end;
$$;
